import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import { ClerkProvider } from "@clerk/nextjs";
import { GeistSans } from "geist/font";
import { type Metadata } from "next";
import TopNav from "./_components/topnav";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { type PropsWithChildren } from "react";
import { Footer } from "./_components/Footer";

export const metadata: Metadata = {
  title: "Gilberts Gallery",
  description: "Generated by You.Run",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

interface RootLayoutProps extends PropsWithChildren {
  modal: React.ReactNode;
}

export default function RootLayout({ children, modal }: RootLayoutProps) {
  return (
    <ClerkProvider>
      <NextSSRPlugin
        /**
         * Simple explanation of what NextSSRPlugin does:
         * Think of this like a security guard that only lets certain people into a party.
         *
         * When someone wants to upload a file, their browser needs to know what kinds of
         * files are allowed (like images only) and how big they can be (like 4MB max).
         *
         * But we don't want to share ALL the secret party details (like where we store the files).
         * So this code only shares the basic rules, keeping the important stuff private!
         */
        routerConfig={extractRouterConfig(ourFileRouter)}
      />
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className={`flex min-h-screen flex-col font-sans text-white`}>
          <TopNav />
          <main className="flex-1">{children}</main>

          {modal}
          <div id="modal-root" />
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
